"""Build a digest email from summaries and cluster data."""

import logging
from datetime import date
from pathlib import Path
from typing import Dict, List, Optional

from jinja2 import Environment, FileSystemLoader

logger = logging.getLogger(__name__)

TEMPLATES_DIR = Path(__file__).parent / "templates"


def build_digest(
    summaries: List[dict],
    clusters: dict,
    digest_date: date,
) -> Dict[str, str]:
    """Build HTML and plain-text digest from summaries and cluster data.

    Returns {"html": str, "text": str, "subject": str}.
    """
    # Extract cluster sub-sections
    top_story = clusters.get("top_story") or {}
    theme_list = clusters.get("clusters") or []
    contradictions = clusters.get("contradictions") or []
    digest_intro = clusters.get("digest_intro") or ""

    # Format date for display
    date_str = digest_date.strftime("%b %-d, %Y")
    newsletter_count = len(summaries)
    theme_count = len(theme_list)

    # Build subject line
    subject = "Your Newsletter Digest \u2014 {}".format(
        digest_date.strftime("%b %-d")
    )
    parts = []
    parts.append("{} newsletter{}".format(
        newsletter_count, "s" if newsletter_count != 1 else ""
    ))
    if theme_count:
        parts.append("{} theme{}".format(
            theme_count, "s" if theme_count != 1 else ""
        ))
    subject += " ({})".format(", ".join(parts))

    # Render HTML
    env = Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        autoescape=True,
    )
    template = env.get_template("digest.html")
    html = template.render(
        subject=subject,
        digest_date=date_str,
        newsletter_count=newsletter_count,
        digest_intro=digest_intro,
        top_story=top_story if top_story else None,
        clusters=theme_list,
        contradictions=contradictions,
    )

    # Build plain-text fallback
    text = _build_plain_text(
        date_str=date_str,
        newsletter_count=newsletter_count,
        digest_intro=digest_intro,
        top_story=top_story,
        clusters=theme_list,
        contradictions=contradictions,
    )

    return {"html": html, "text": text, "subject": subject}


def _build_plain_text(
    date_str: str,
    newsletter_count: int,
    digest_intro: str,
    top_story: Optional[dict],
    clusters: List[dict],
    contradictions: List[dict],
) -> str:
    """Generate a plain-text version of the digest."""
    lines = []
    lines.append("NEWSLETTER DIGEST")
    lines.append("{} - {} newsletter{}".format(
        date_str, newsletter_count, "s" if newsletter_count != 1 else ""
    ))
    lines.append("=" * 60)

    if digest_intro:
        lines.append("")
        lines.append(digest_intro)

    if top_story and top_story.get("name"):
        lines.append("")
        lines.append("YOUR TOP STORY")
        lines.append("-" * 40)
        lines.append(top_story["name"])
        if top_story.get("why"):
            lines.append(top_story["why"])
        if top_story.get("sources"):
            lines.append("From: {}".format(", ".join(top_story["sources"])))

    if clusters:
        lines.append("")
        lines.append("TODAY'S TRENDS")
        lines.append("-" * 40)
        for i, cluster in enumerate(clusters, 1):
            lines.append("")
            lines.append("{}. {}".format(i, cluster.get("name", "")))
            if cluster.get("synthesis"):
                lines.append("   {}".format(cluster["synthesis"]))
            if cluster.get("cross_theme_note"):
                lines.append("   {}".format(cluster["cross_theme_note"]))
            if cluster.get("sources"):
                lines.append("   Sources: {}".format(", ".join(cluster["sources"])))
            if cluster.get("read_more_url"):
                lines.append("   Read more: {}".format(cluster["read_more_url"]))

    if contradictions:
        lines.append("")
        lines.append("DIFFERENT TAKES")
        lines.append("-" * 40)
        for item in contradictions:
            lines.append("")
            lines.append(item.get("topic", ""))
            for pos in item.get("positions", []):
                lines.append("  {}: {}".format(
                    pos.get("source", ""), pos.get("position", "")
                ))

    lines.append("")
    lines.append("---")
    lines.append("Generated by Newsletter Digest")
    return "\n".join(lines)
